<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head"><b>MagetSync Mappings (For existing Etsy stores)</b></h3></td>
        </tr>
        </tbody></table>
</div>

<div class='messageMapping'><ul class='messages'>
        <li class='notice-msg'>
            <ul>
                <li>This section is only for Merchants who wish to synchronise their products from an existing Etsy Shop. Make sure you've configured MagetSync and have authorized it beforehand.</li>
            </ul>
        </li>
    </ul>
</div>