<div id='messages'><ul class='messages'><li class='notice-msg'>
            <ul>
                <li>This page contains the list of your chosen products to be in sync with your Etsy Shop. Before syncing these, please verify you have created at least one Shop Section and a Shipping template. <a href="http://support.magetsync.com/hc/en-us/articles/206550348" class="link-store-scope" title="What is this?" target="_blank">Help</a></li>
                <li> Click on any of the products below to fill out additional attributes required by Etsy. Tip: Multiple products can be updated at once by selecting the 'Update Attributes' dropdown option</li>
            </ul>
        </li>
    </ul>
</div>