<div id='messages'>
    <ul class='messages'>
        <li class='notice-msg'>
            <ul>
                <li>This page contains the list of products you've chosen to sync with Etsy. Before
                    syncing these, please verify you have created at least one Shop Section, a Shipping template and
                    filled out all required Etsy attributes. <a
                        href="http://support.magetsync.com/hc/en-us/articles/206550348" class="link-store-scope"
                        title="What is this?" target="_blank">Help</a></li>
            </ul>
        </li>
    </ul>
</div>