<div class='box'>
    <?php echo Mage::helper('magetsync')->__('Add additional information and attributes to your Etsy listings by creating re-usable notes. 
        These could appear before or after each product description. Useful for general information about your shop, shipping info or other policies, etc. 
        <a href="http://support.magetsync.com/hc/en-us/articles/207288977" class="link-store-scope" title="What is this?" target="_blank">Help</a>')
    ?>
</div>
