<?php

/**
 * @copyright  Copyright (c) 2015 Merchant-e
 *
 * Class for creating Shipping Template form
 * Class Merchante_MagetSync_Block_Adminhtml_Global_ShippingTemplate_Edit_Tab_Form
 */
class Merchante_MagetSync_Block_Adminhtml_Global_ShippingTemplate_Edit_Tab_Form extends Mage_Adminhtml_Block_Widget_Form
{
    /**
     * Method for creating form inputs
     * @return Mage_Adminhtml_Block_Widget_Form
     */
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form();
        $this->setForm($form);

        $fieldset = $form->addFieldset('global_shippingtemplate_form',
            array('legend'=> Mage::helper('magetsync')->__("Shipping Profile Information")));

        $idShipping = $fieldset->addField('shipping_template_id', 'text',
            array(
                'label' => Mage::helper('magetsync')->__("Shipping ID"),
                'required' => false,
                'readonly' => true,
                'class' => 'disabled',
                'name' => 'shipping_template_id',
                'after_element_html' => '<br><small>'.Mage::helper('magetsync')->__("This value is generated by Etsy").'</small>',
            ));

        $title = $fieldset->addField('title', 'text',
            array(
                'label' => Mage::helper('magetsync')->__("Title"),
                'class' => 'required-entry',
                'required' => true,
                'name' => 'title',
            ));

        $processing = $fieldset->addField('processing', 'select', array(
            'label'     => Mage::helper('magetsync')->__("Processing Time"),
            'name'      => 'processing',
            'class'  => 'validate-select',
            'required' => true,
            'values'    => Mage::getModel('magetsync/processingTime')->toOptionArray(),
        ));

        $min = $fieldset->addField('min_processing_days', 'text',
            array(
                'label' => Mage::helper('magetsync')->__("Min"),
                'class' => 'required-entry validate-digits validate-digits-range digits-range-1-10',
                'required' => true,
                'name' => 'min_processing_days',
            ))->setAfterElementHtml("
                <small>".Mage::helper('magetsync')->__("This value must be between 1 to 10")."</small>
                <script type=\"text/javascript\">
                $('min_processing_days').observe('blur', function(e){
                        var min = document.getElementById('min_processing_days').value;
                        var max = document.getElementById('max_processing_days').value;

                        //if(min>10){document.getElementById('min_processing_days').value = '';}

                            if(max !== undefined)
                            {
                                var valMin = parseInt(min);
                                var valMax = parseInt(max);
                                if(isNaN(valMin))
                                {
                                    document.getElementById('min_processing_days').value = '';
                                    return false;
                                }
                                if(valMin >= valMax)
                                {
                                   document.getElementById('max_processing_days').value = '';
                                   return false;
                                }
                            }
                            return true;
                    });
                         </script>");

        $max = $fieldset->addField('max_processing_days', 'text',
            array(
                'label' => Mage::helper('magetsync')->__("Max"),
                'class' => 'required-entry validate-digits validate-digits-range digits-range-1-10',
                'required' => true,
                'name' => 'max_processing_days',
            ))->setAfterElementHtml("
                <small>".Mage::helper('magetsync')->__("This value must be between 1 to 10")."</small>
                <script type=\"text/javascript\">
                    $('max_processing_days').observe('blur', function(e){
                       var min = document.getElementById('min_processing_days').value;
                       var max = document.getElementById('max_processing_days').value;
                            if(min !== undefined)
                            {
                                var valMin = parseInt(min);
                                var valMax = parseInt(max);
                                  if(isNaN(valMax)){
                                    document.getElementById('max_processing_days').value = '';
                                    return false;
                                }
                                if(valMin >= valMax)
                                {
                                   document.getElementById('min_processing_days').value = '';
                                   return false;
                                }
                            }
                            return true;
                    });
                </script>");

        $frequency = $fieldset->addField('frequency', 'select', array(
            'label'     => Mage::helper('magetsync')->__("Frequency"),
            'name'      => 'frequency',
            'values'    => array(
                'D' => 'business days',
                'W'   => 'weeks'
            )
        ));

        $country = $fieldset->addField('origin_country_id', 'select', array(
            'name'  => 'origin_country_id',
            'label'     => Mage::helper('magetsync')->__("Ships from"),
            'class' => 'validate-select',
            'required' => true,
            'values'    => Mage::getModel('magetsync/countryEtsy')->toOptionArray(),
        ));

        /*********************************
         * Shipping entries Grid (.phtml)
         ********************************/
        $entry_field = $fieldset->addField('shipping_entry', 'editor', array(
            'name'      => 'shipping_entry',
            'label'     => Mage::helper('magetsync')->__("Shipping entries"),
            'class' => 'required-entry',
            'required'  => true
        ));
        $shippingEntry = $form->getElement('shipping_entry');
        $shippingEntry->setRenderer(
            $this->getLayout()->createBlock('magetsync/adminhtml_global_shippingTemplate_edit_renderer_shippingTemplate')
        );
        /***********************************************************************/

        if ( Mage::registry('magetsync_shippingtemplate') )
        {
            $form->setValues(Mage::registry('magetsync_shippingtemplate')->getData());
        }

        $this->setForm($form);
        $this->setChild('form_after', $this->getLayout()->createBlock('adminhtml/widget_form_element_dependence')
                ->addFieldMap($idShipping->getHtmlId(), $idShipping->getName())
                ->addFieldMap($title->getHtmlId(), $title->getName())
                ->addFieldMap($processing->getHtmlId(), $processing->getName())
                ->addFieldMap($min->getHtmlId(), $min->getName())
                ->addFieldDependence(
                    $min->getName(),
                    $processing->getName(),
                    -2
                )
                ->addFieldMap($frequency->getHtmlId(), $frequency->getName())
                ->addFieldDependence(
                    $frequency->getName(),
                    $processing->getName(),
                    -2
                )
                ->addFieldMap($max->getHtmlId(), $max->getName())
                ->addFieldDependence(
                    $max->getName(),
                    $processing->getName(),
                    -2
                )
                ->addFieldMap($country->getHtmlId(), $country->getName())
                ->addFieldMap($entry_field->getHtmlId(), $entry_field->getName())
        );

        return parent::_prepareForm();
    }
}